" Vundle confguration
filetype off
set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#rc()

Plugin 'scrooloose/nerdtree'

call vundle#end()
filetype plugin indent on

" Global preferences
set number
set colorcolumn=80

" Indention
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set pastetoggle=<F3>

" Mappings
nmap <F2> :NERDTree<cr>
